# KNN algorithm using MNIST dataset

In [4]:
import pandas as pd
import numpy as np
#loading mnist_train dataset
df_train=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\mnist_train.csv")
df_test=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\mnist_test.csv")
#shape of a data
print(df_train.shape)
print(df_test.shape)

(60000, 785)
(10000, 785)


In [5]:
df_test.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      7    0    0    0    0    0    0    0    0    0  ...      0      0   
1      2    0    0    0    0    0    0    0    0    0  ...      0      0   
2      1    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      4    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [6]:
#no. of instances belong each 
df_train.groupby('label').size()

label
0    5923
1    6742
2    5958
3    6131
4    5842
5    5421
6    5918
7    6265
8    5851
9    5949
dtype: int64

In [7]:
#making a numpy array
import numpy as np
x_train=df_train.to_numpy()
x_test=df_test.to_numpy()
#x_train

In [8]:
#unique values
y_train=np.unique(x_train[:,0])
y_train

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [9]:
testing_data=list(x_test[:,1:])

In [10]:
#creating clusters
c={}
for n in y_train:
    c[n]=x_train[np.where(x_train[:,0]==n)][:,1:]
c[9]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
import matplotlib.pyplot as plt
df_train=pd.DataFrame(dict(x=x_train[:,0],y=x_train[:,1]))
plt.scatter(x,y)
plt.show()

NameError: name 'x' is not defined

In [8]:
#mean of cluster
mean={}
for i in y_train:
    mean[i]=[np.mean(c[i],axis=0)]

In [9]:
#distance
#calculating distance from a test point
def test(test_point):
    x = [i for i in c.keys()]    
    y = []
    for i in mean.keys():
        y.append(np.sqrt(np.sum(np.square(np.subtract(mean[i],test_point)))))  #distance from each cluster
    dist= dict(zip(x,y))
    for key in dist.keys():
        if dist[key]==min(dist.values()):
            return key

In [10]:
#calculating output
output = np.empty(0)
for data_point in testing_data:
    output = np.append(output,test(data_point))
print(output)

[7. 2. 1. ... 4. 5. 6.]


In [11]:
#creating label
y_test=x_test[:,0]

In [12]:
#calculating accuracy
correct=0
total=10000
for i in range(len(y_test)):
    if y_test[i]==output[i]:
        correct+=1
    else:
        continue
correct

8203

In [13]:
#converting to percentage
accuracy=(correct/total)*100
print(f"Accuracy is = {accuracy} %")

Accuracy is = 82.03 %


In [ ]:
10 data points
5 classes 
first 2 class we make a mistake half of a tym during pred
3 class ki correct
what is the end
to know mistakes we use validation
