# Modified clustering algorithm for the MNIST data using bootstrap sampling

In [4]:
import pandas as pd
import numpy as np
#loading mnist_train dataset
df_train=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\mnist_train.csv")
df_train= df_train.sample(frac=1)   #shuffling of data
df_test=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\mnist_test.csv")
print(df_train.shape)
print(df_test.shape)

(60000, 785)
(10000, 785)


In [5]:
#df_test.head()

In [6]:
#making a numpy array
x_train=df_train.to_numpy()
x_test=df_test.to_numpy()
#unique values
y_train=np.unique(x_train[:,0])
y_train

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [7]:
testing_data=x_test[:,1:]
print(testing_data)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
cluster = {}
clus = df_train.groupby('label')
for groups , data in clus:
    cluster[groups] = np.array(data.iloc[:,1:])
#cluster

In [9]:
labels=list(cluster.keys())
labels

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
#creating 5 samples from each cluster splitting 20 prcnt of data
sampling = {}
for i in range(len(labels)):
    sampling[i] = np.array_split(cluster[i] , 5)

In [8]:
#mean of subset
m = {}
for i in range(len(sampling)):
    sub = []
    for j in sampling[i]:
        sub.append([j[:,k].mean() for k in range(j.shape[1])])
    m[i] = np.array(sub)

In [9]:
def distance(a,b):
    return np.sqrt(np.sum(np.square(np.subtract(a,b)))).round(4)

In [10]:
def function(test_point):
    dist = {}
    for i in range(10):
        for j in m[i]:
            dis = distance(j,test_point)
            dist[dis] = i
    d = []
    for i in sorted(dist)[:5]:
        d.append(dist[i])
        return max(d)

In [11]:
output = np.empty(0)
for data_point in testing_data:
    output = np.append(output,function(data_point))
print(output)

[7. 2. 1. ... 4. 5. 6.]


In [12]:
#creating label
y_test=(df_test.iloc[:,0])

In [13]:
#calculating accuracy
correct=0
total=10000
for i in range(len(y_test)):
    if y_test[i]==output[i]:
        correct+=1
    else:
        continue
correct

8258

In [14]:
#converting to percentage
accuracy=(correct/total)*100
print(f"Accuracy is = {accuracy} %")

Accuracy is = 82.58 %


In [ ]:
#techn=bootstrap , ensloving ,k fold validatn
