# Naive Bayes from sklearn and scratch

Naive Bayes from scratch

In [89]:
#creating a dataset
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
df_train=pd.DataFrame({'GENE A':[1,1,0,-1,-1,-1,0,1,1,-1,1,0,0,-1],'GENE B':[1,1,1,0,-1,-1,-1,0,-1,0,0,0,1,0],'GENE C':[1,1,1,1,0,0,0,1,0,0,0,1,0,1],'GENE D':[0,1,0,0,0,1,1,0,0,0,1,1,0,1],'y':[0,0,1,1,1,0,1,0,1,1,1,1,1,0]})
df_test=pd.DataFrame({'GENE A':[1],'GENE B':[12],'GENE C':[1],'GENE D':[1]})
df_train=df_train.to_numpy()
df_test=df_test.to_numpy()          #n=0,t=1

In [90]:
x=df_train[:,0:4]
yt=df_train[:,-1]

In [91]:
x

array([[ 1,  1,  1,  0],
       [ 1,  1,  1,  1],
       [ 0,  1,  1,  0],
       [-1,  0,  1,  0],
       [-1, -1,  0,  0],
       [-1, -1,  0,  1],
       [ 0, -1,  0,  1],
       [ 1,  0,  1,  0],
       [ 1, -1,  0,  0],
       [-1,  0,  0,  0],
       [ 1,  0,  0,  1],
       [ 0,  0,  1,  1],
       [ 0,  1,  0,  0],
       [-1,  0,  1,  1]], dtype=int64)

In [92]:
yt

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [93]:
normal = 0
tumor = 0
for i  in range(0,14):
    if y[i] == 0:
        normal += 1 
    else:
        tumor += 1
P_N = normal/(normal+tumor)
P_T = tumor/(normal+tumor)
print('P(Normal)' , P_N)
print('P(Tumor)' , P_T )

P(Normal) 0.35714285714285715
P(Tumor) 0.6428571428571429


In [111]:
#x1=n
n0=0
n1=0
n2=0
for i  in range(0,14):
    if x[i][0] == 0 and y[i] == 0:
        n0 += 1
    elif x[i][0] == 1 and y[i] == 0:
        n1 += 1
    elif x[i][0] == -1 and y[i] == 0:
        n2 +=1

In [112]:
normal1=[n0,n1,n2]

In [113]:
#x1=t
t0=0
t1=0
t2=0
for i  in range(0,14):
    if x[i][0] == 0 and y[i] == 1:
        t0 += 1
    elif x[i][0] == 1 and y[i] == 1:
        t1 += 1
    elif x[i][0] == -1 and y[i] == 1:
        t2 +=1

In [114]:
tumor1=[t0,t1,t2]

In [115]:
#x2=n
n0_2=0
n1_2=0
n2_2=0
for i  in range(0,14):
    if x[i][0] == 0 and y[i] == 0:
        n0_2 += 1
    elif x[i][0] == 1 and y[i] == 0:
        n1_2 += 1
    elif x[i][0] == -1 and y[i] == 0:
        n2_2+=1

In [116]:
normal2=[n0_2,n1_2,n2_2]

In [117]:
#x2=t
t0_2=0
t1_2=0
t2_2=0
for i  in range(0,14):
    if x[i][0] == 0 and y[i] == 1:
        t0_2 += 1
    elif x[i][0] == 1 and y[i] == 1:
        t1_2 += 1
    elif x[i][0] == -1 and y[i] == 1:
        t2_2 +=1

In [118]:
tumor2=[t0_2,t1_2,t2_2]

In [119]:
#x3=n
n0_3=0
n1_3=0
n2_3=0
for i  in range(0,14):
    if x[i][0] == 0 and y[i] == 0:
        n0_3 += 1
    elif x[i][0] == 1 and y[i] == 0:
        n1_3 += 1
    elif x[i][0] == -1 and y[i] == 0:
        n2_3 +=1

In [120]:
normal3=[n0_3,n1_3,n2_3]

In [121]:
#x3=t
t0_3=0
t1_3=0
t2_3=0
for i  in range(0,14):
    if x[i][0] == 0 and y[i] == 1:
        t0_3 += 1
    elif x[i][0] == 1 and y[i] == 1:
        t1_3 += 1
    elif x[i][0] == -1 and y[i] == 1:
        t2_3 +=1

In [122]:
tumor3=[t0_3,t1_3,t2_3]

In [124]:
#x4=n
n0_4=0
n1_4=0
n2_4=0
for i  in range(0,14):
    if x[i][0] == 0 and y[i] == 0:
        n0_4 += 1
    elif x[i][0] == 1 and y[i] == 0:
        n1_4 += 1
    elif x[i][0] == -1 and y[i] == 0:
        n2_4 +=1

In [125]:
normal4=[n0_4,n1_4,n2_4]

In [126]:
#x4=t
t0_4=0
t1_4=0
t2_4=0
for i  in range(0,14):
    if x[i][0] == 0 and y[i] == 1:
        t0_4 += 1
    elif x[i][0] == 1 and y[i] == 1:
        t1_4 += 1
    elif x[i][0] == -1 and y[i] == 1:
        t2_4 +=1

In [127]:
tumor4=[t0_4,t1_4,t2_4]

In [128]:
#normal=0 and 1 means for feature 1
print(normal1)
print(tumor1)
print(normal2)
print(tumor2)
print(normal3)
print(tumor3)
print(normal4)
print(tumor4)

[0, 3, 2]
[4, 2, 3]
[0, 3, 2]
[4, 2, 3]
[0, 3, 2]
[4, 2, 3]
[0, 3, 2]
[4, 2, 3]


In [ ]:
def test():
    normal_test=[]
    tumor_test=[]
    for i in range():
        normal_test.append
        

Naive Bayes from sklearn

In [60]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(x, yt)

#Predict the response for test dataset
y_pred = gnb.predict(xt)

In [66]:
y_pred #that is normal

array([0], dtype=int64)